language: python

env:
    global: PYTHON_VERSION=3.7

matrix:
    include:
        - os: linux
          env: MNE_VERSION=stable

        - os: linux
          env: MNE_VERSION=master

before_install:
  - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
install:
  - conda update --yes --quiet conda
  - conda create -n testenv --yes pip python=${PYTHON_VERSION}
  - source activate testenv
  - conda install --yes --quiet numpy scipy scikit-learn matplotlib joblib
  - pip install pytest==5.3.5 pytest-cov pytest-sugar coverage
  - pip install -q flake8 check-manifest h5py
  - if [ "${MNE_VERSION}" == "stable" ]; then
      pip install mne;
    else
      pip install mne<0.20
    fi;
  - python setup.py install
script:
  - python -m pytest autoreject --cov=./autoreject --cov-report=xml --cov-config=.coveragerc --verbose
  - flake8 --count .
  - check-manifest --ignore .circleci/*,doc
after_success:
  - bash <(curl -s https://codecov.io/bash)
