language: python

env:
  - PYTHON_VERSION=3.5

before_install:
  - wget -q https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
install:
  - conda update --yes --quiet conda
  - conda create -n testenv --yes pip python=${PYTHON_VERSION}
  - source activate testenv
  - conda install --yes --quiet numpy scipy scikit-learn matplotlib joblib
  - pip install pytest pytest-cov pytest-sugar pytest-faulthandler
  - pip install -q flake8 check-manifest h5py
  - pip install https://api.github.com/repos/mne-tools/mne-python/zipball/master
  - python setup.py install
script:
  - pytest --cov-report=xml --cov=autoreject autoreject/tests/
  - flake8 --count .
  - check-manifest --ignore .circleci*,doc
after_success:
  - bash <(curl -s https://codecov.io/bash)
